CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    stock INTEGER NOT NULL,
    currency VARCHAR(3) NOT NULL,
    CONSTRAINT uk_products_reference UNIQUE (reference),
    CONSTRAINT ck_products_price_non_negative CHECK (price >= 0),
    CONSTRAINT ck_products_stock_non_negative CHECK (stock >= 0)
);

CREATE TABLE authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    author_type VARCHAR(20) NOT NULL,
    CONSTRAINT ck_authors_author_type
        CHECK (author_type IN ('AMATEUR', 'PROFESSIONAL'))
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    notation INTEGER NOT NULL,
    reviewed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    comment TEXT NOT NULL,
    CONSTRAINT fk_reviews_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_author
        FOREIGN KEY (author_id) REFERENCES authors (id),
    CONSTRAINT ck_reviews_notation CHECK (notation BETWEEN 1 AND 5)
);

CREATE INDEX idx_reviews_product_id ON reviews (product_id);
CREATE INDEX idx_reviews_author_id ON reviews (author_id);
CREATE INDEX idx_reviews_reviewed_at ON reviews (reviewed_at);
